### ISSUE TITLE
Saving a Swift double does not work

### ISSUE THREAD

**Issue by dominik-hadl** [nodes-ios/Cashier#19]
Saving a Swift's Double type into NOPersistentStore and then retrieving immediately after does not seem to work.

**Comment by mariusc** [comment]
@nickskull Can you check out the `feature/swiftDoubleTests` branch https://github.com/nodes-ios/Cashier/tree/feature/swiftDoubleTest? 

I added new tests for Swift types and structs and they all pass (I haven't set up Travis to build that branch, so you'd have to run the tests locally). Unless I overlooked something in the tests, caching a Double in NOPersistentStore seems to work. 

Can you give more details about your issue? Did you serialize / deserialize it? Could the error be in the CashierExtensions instead?

**Comment by dominik-hadl** [comment]
Interesting. I was doing the exact same as you've done in the tests - only difference being, that I didn't use the default cache but "cacheWithName" instead (which is also what we should be doing in the tests, otherwise there might be collisions). We should get that branch merged in. :)

**Comment by mariusc** [comment]
Yeah, that was also my plan, to get the branch merged in; I'll update the tests to not use the default cache and make a PR

**Comment by dominik-hadl** [comment]
Since the tests pass, let's close this :)
