### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by dominik-hadl** [nodes-ios/Cashier#2]

**Comment by mariusc** [comment]
So far I have "An easy to use object cache for iOS". Any other ideas? Anything against this one? @nodes-ios/developer-team

**Comment by dominik-hadl** [comment]
Might be a good idea to mention it's compatible with Swift and what iOS version.

**Comment by mariusc** [comment]
In the repo description here? 
![image](https://cloud.githubusercontent.com/assets/844175/13698814/b97fe0dc-e776-11e5-9e7e-f459e5833b9a.png)
I think Swift compatibility and iOS versions are better suited for the first line of the Readme.

**Comment by dominik-hadl** [comment]
Hmm, you're right. 

But what we should mention is that it has 2 layers and that it also includes persistent store.

**Comment by mariusc** [comment]
So far, we're going with "An easy to use 2-layered object cache for iOS". Due to lack of ideas and lack of a better alternative, I'm closing this issue. If anyone is struck suddenly inspiration, just reopen it.
