### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/Cashier#6]
- [x] tests for NOCache (renamed to Cashier)
  - [x] test object insertion in cache
  - [x] test object fetching from cache
  - [x] test object deletion from cache
  - [x] test cache clearing
  - [x] test image insertion in cache
  - [x] test image deletion from cache
  - [x] test image fetching from cache
  - [x] test cache is automatically cleared on memory warning
  - [x] test cache persistence across versions
  - [x] test cache lifespan
- [x] tests for NOPersistentStore

Working on branch https://github.com/nodes-ios/Cashier/tree/mariusc-tests for Cashier tests

**Comment by mariusc** [comment]
I'm not really sure how to test the cache persistence across versions. Looks like I would need to simulate a change in the CFBundleShortVersionString, and I don't know how to do that. @nodes-ios/developer-team any suggestions on this one?

**Comment by dominik-hadl** [comment]
Look at how the cache [compares versions](https://github.com/nodes-ios/Cashier/blob/mariusc-tests/Cashier/Cashier.m#L127). I think you should be able to manually change that in `NSUserDefaults`, so you could make the cache think there's new version :)

**Comment by mariusc** [comment]
I made the change manually in NSUserDefaults, but my test failed. So I investigated a bit more and saw that `[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"]` is nil and [[NSBundle mainBundle] infoDictionary] is an empty dictionary.

![image](https://cloud.githubusercontent.com/assets/844175/13724673/7c3f382c-e88d-11e5-936e-fc5c04db2bce.png).

**Comment by dominik-hadl** [comment]
That is most likely because of the tests bundle. As a quick hack, swizzling the infoDictionary getter method of NSBundle with a custom implementation would work. Then you can easily control version numbers returned from your custom infoDictionary.

**Comment by mariusc** [comment]
Made PR for Cashier tests https://github.com/nodes-ios/Cashier/pull/13. NOPersistentStore ignored for the moment

**Comment by mariusc** [comment]
We have added some tests for NOPersistentStore in the Swift types tests. As always, tests can always be improved. But it's safe to close this issue now.
